# Generated by Django 3.2.4 on 2021-07-02 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.CharField(max_length=100)),
                ('start_break', models.CharField(blank=True, max_length=100, null=True)),
                ('end_break', models.CharField(blank=True, max_length=100, null=True)),
                ('end_work', models.CharField(blank=True, max_length=100, null=True)),
                ('away', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_break', models.CharField(blank=True, max_length=100, null=True)),
                ('end_break', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
